# Support Vector Machines (SVM) with Wine Dataset
---
In this notebook, you'll apply Support Vector Machines (SVMs) to a more complex classification problem: classifying different types of wine based on their chemical properties.

## Step 1: Dataset Overview
We'll be using the [Wine Dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_wine.html) from scikit-learn. It contains 178 samples of wine with 13 chemical analysis features. The target is to classify the wines into three different cultivars.

**Features include**: alcohol content, malic acid, ash, magnesium, total phenols, flavanoids, non-flavanoid phenols, proanthocyanins, color intensity, hue, etc.

**Goal**: Train an SVM to predict the correct wine class from these features.

## Step 2: Install Required Libraries
If necessary, install missing libraries using:
```bash
pip install pandas numpy seaborn matplotlib scikit-learn
```

## Step 3: Import Libraries

In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

## Step 4: Load and Explore the Wine Dataset

In [8]:
wine = load_wine()
X = pd.DataFrame(wine.data, columns=wine.feature_names)
y = pd.Series(wine.target, name='target')
X['target'] = y
X.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0


## Step 5: Prepare Data (Train/Validation Split)
We will split the dataset into training (70%) and validation (30%) sets, and scale the features.

In [9]:
# Separate features and target
X = X.drop(columns=['target'])

# Split into train and validation
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

## Step 6: Train SVM with Linear Kernel

In [10]:
svm_linear = SVC(kernel='linear')
svm_linear.fit(X_train_scaled, y_train)
y_pred_linear = svm_linear.predict(X_val_scaled)

print("Confusion Matrix:")
print(confusion_matrix(y_val, y_pred_linear))
print("\nClassification Report:")
print(classification_report(y_val, y_pred_linear))

Confusion Matrix:
[[18  0  0]
 [ 1 20  0]
 [ 0  1 14]]

Classification Report:
              precision    recall  f1-score   support

           0       0.95      1.00      0.97        18
           1       0.95      0.95      0.95        21
           2       1.00      0.93      0.97        15

    accuracy                           0.96        54
   macro avg       0.97      0.96      0.96        54
weighted avg       0.96      0.96      0.96        54



## Step 7: Train SVM with RBF Kernel

In [11]:
svm_rbf = SVC(kernel='rbf')
svm_rbf.fit(X_train_scaled, y_train)
y_pred_rbf = svm_rbf.predict(X_val_scaled)

print("Confusion Matrix:")
print(confusion_matrix(y_val, y_pred_rbf))
print("\nClassification Report:")
print(classification_report(y_val, y_pred_rbf))

Confusion Matrix:
[[18  0  0]
 [ 0 21  0]
 [ 0  1 14]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       0.95      1.00      0.98        21
           2       1.00      0.93      0.97        15

    accuracy                           0.98        54
   macro avg       0.98      0.98      0.98        54
weighted avg       0.98      0.98      0.98        54



## Step 8: Accuracy Comparison

In [12]:
print(f"Linear Kernel Accuracy: {accuracy_score(y_val, y_pred_linear):.2f}")
print(f"RBF Kernel Accuracy: {accuracy_score(y_val, y_pred_rbf):.2f}")

Linear Kernel Accuracy: 0.96
RBF Kernel Accuracy: 0.98


## Investigation tasks

**Task 1**: Research and explain what a kernel is in SVMs and the different kernels that Sklearn supports.

<span style="color:red">(1 mark)</span>

<span style="color:red">Your answer goes here</span>

**Task 2**: Train a SVM with a different kernel.

<span style="color:red">(1 mark)</span>

In [13]:
# Your answer goes here

**Task 3**: Generate a correlation matrix between all the features of the dataset and the target (you can use AI for this step), interpret the results and train a new SVM using only the 5 features with the highest correlation.

<span style="color:red">(1 mark)</span>

In [14]:
# Your answer goes here

<span style="color:red">Your answer goes here</span>

**Task 4**: Compare the results of this new algorithm with the ones trained on steps 6 and 7.

<span style="color:red">(1 mark)</span>

In [15]:
# Your answer goes here

<span style="color:red">Your answer goes here</span>

**Task 5**: Make predictions on the training set and compare the performance between the training and validation. Based on these results, determine if the model suffers from overfitting or underfitting.

<span style="color:red">(1 mark)</span>

In [16]:
# Your answer goes here

<span style="color:red">Your answer goes here</span>

**Bonus**: Research what feature scaling is and explain why it is important to apply it to this dataset as part of the data cleaning process.

<span style="color:red">(0.5 marks)</span>


**Bonus**: Research what PCA. Reduce dimensionality using PCA and visualize 2D scatter plots colored by class.

<span style="color:red">(0.5 marks)</span>